name: jetbrains/tag-current-build
title: Tag current build
version: 1.0.1
description: |
  Tags the current build. 
  If you need to tag specific builds by their IDs, use the 'tag-build' recipe instead.
inputs:
  - env.input_tags:
      type: text
      required: true
      label: Tags
      description: | 
        A newline-delimited list of tags to add.
steps:
  - name: Add custom tags to the current build
    kotlin-script: !include src.main.kts
