name: jetbrains/download-from-s3
version: 1.0.0
description: |
  Retrieves an object from AWS S3 and saves it to a specified local destination. 
  Allows you to download both individual files and AWS S3 folders.
  
  AWS credentials and AWS region can be provided in recipe settings.
  If credentials are not specified, the default AWS credentials provider chain will be used.
  Alternatively, the "Amazon Web Services (AWS)" connection can be configured at the project level and accessed via the "AWS Credentials" build feature.
inputs:
  - env.input_source:
      type: text
      required: true
      label: Source
      description: |
        The S3 path of the object to download (e.g. s3://bucket/path/to/file).
  - env.input_target:
      type: text
      required: true
      label: Target
      description: |
        The local file or directory path where the downloaded object will be stored.
        Accepts absolute (/path/to/file, C:\path\to\file) and relative to the agent working directory (path/to/file) paths.
  - env.input_aws_access_key_id:
      type: password
      required: false
      label: Access key ID
      description: |
        The optional AWS account access key ID.
  - env.input_aws_secret_access_key:
      type: password
      required: false
      label: Secret access key
      description: |
        The optional AWS account secret access key.
  - env.input_aws_region:
      type: text
      required: false
      label: AWS region
      description: |
        The optional AWS region.
steps:
  - name: Download from S3
    kotlin-script: !include src.main.kts
