name: jetbrains/upload-to-s3
version: 1.0.0
description: |
  Uploads a local file or directory to the AWS S3 bucket. 
  If a directory is selected, TeamCity will upload its contents directly to the target path 
  without creating a corresponding directory in S3.
inputs:
  - env.input_source:
      type: text
      required: true
      label: Source
      description: |
        The local file or directory path to be uploaded.
        Accepts absolute (/path/to/file, C:\path\to\file) and relative to the agent working directory (path/to/file) paths.
  - env.input_target:
      type: text
      required: true
      label: Target
      description: |
        The destination S3 path (e.g. s3://bucket/path/to/file).
steps:
  - name: Upload to S3
    kotlin-script: !include src.main.kts
