name: jetbrains/add-to-path
title: Prepend to PATH env variable
version: 1.0.1
description: |
  Temporarily prepends a specified directory to the PATH environment variable during the build process, ensuring its executables take precedence.
inputs:
  - env.input_path:
      type: text
      required: true
      label: Path
      description: The directory path to prepend to the PATH environment variable.
steps:
  - name: Prepend PATH environment variable
    kotlin-script: !include src.main.kts
