name: jetbrains/dynamic-build-chain-settings-generator
title: Dynamic Build Chain Settings Generator
version: 1.0.0
description: |
  A recipe that can be used to dynamically generate settings for a build chain.
  This recipe executes the generation step and publishes the settings as an artifact.
  This recipe prepares an environment so that the DSL runs as if it were generating settings
  within the context of your project. To do so, it needs credentials with EDIT permissions to
  the project.
inputs:
  - env.input_server_url:
      type: text
      required: false
      label: Server URL
      description: |
        The full TeamCity server URL (for example, https://teamcity.jetbrains.com). 
        The default value is %teamcity.serverUrl%.
      default: "%teamcity.serverUrl%"
  - env.input_project_id:
      type: text
      required: false
      label: Project ID
      description: |
        The project ID whose generated configs are relative to.
      default: "%teamcity.project.id%"
  - env.input_params:
      type: text
      required: false
      label: DSL parameters
      description: |
        A list of comma-delimited 'name=value' parameters to write to 
        the 'params.properties' file. (Read this file to create parameter-based conditions for the generator.)
  - env.input_agent_token:
      type: password
      required: true
      label: Authentication token
      description: |
        Bearer token with EDIT permissions to the project. 
        This token will be used to download the context to generate settings.
  - env.input_settings_directory:
      type: text
      required: false
      label: Settings directory
      description: |
        The directory where the versioned settings are currently.
        If not specified, the default is '.teamcity'.
      default: ".teamcity"
  - env.input_maven_tool_path:
      type: text
      required: false
      label: Maven tool path
      description: |
        The path to the Maven tool to use for the generation of the versioned settings.
        If not specified, the default is '%teamcity.tool.maven3_9%'.
      default: "%teamcity.tool.maven3_9%"
  - env.input_java_home:
      type: text
      required: false
      label: Java Home
      description: |
        The path to the Java home to use for the generation of the versioned settings.
      default: "%teamcity.agent.jvm.java.home%"
  - env.input_additional_maven_arguments:
      type: text
      required: false
      label: Additional Maven arguments
      description: |
        A list of comma-delimited 'name=value' parameters without the '-D' prefix
        to use as additional Maven arguments to pass to the Maven command.
steps:
  - name: Generate Settings
    kotlin-script: !include src.main.kts