name: jetbrains/aws-cli-docker
version: 1.0.0
description: |
  Runs AWS CLI command from Docker container.
container:
  image: public.ecr.aws/aws-cli/aws-cli
  platform: linux
inputs:
  - env.input_command:
      type: text
      required: true
      label: Command
      description: The AWS CLI command to run, e.g. "aws s3 cp build.zip s3://bucket".
  - env.input_aws_access_key_id:
      type: password
      required: false
      label: Access key ID
      description: |
        The optional AWS account access key ID.
  - env.input_aws_secret_access_key:
      type: password
      required: false
      label: Secret access key
      description: |
        The optional AWS account secret access key.
  - env.input_aws_region:
      type: text
      required: false
      label: AWS region
      description: |
        The optional AWS region.
steps:
  - name: Run command
    script: !include script.sh